"""Constants for the Compleo Wallbox integration."""

DOMAIN = "compleo_wallbox"
DEFAULT_SCAN_INTERVAL = 30
DEFAULT_PORT = 502
DEFAULT_NAME = "Compleo Wallbox"

# --- REGISTER KONFIGURATION ---
REG_SYS_POWER_LIMIT = 0x0000
REG_SYS_MAX_SCHIEFLAST = 0x0002
REG_SYS_FALLBACK_POWER = 0x0003
REG_SYS_FW_PATCH = 0x0006
REG_SYS_FW_MAJOR = 0x0007
REG_SYS_NUM_POINTS = 0x0008

REG_SYS_TOTAL_POWER_READ = 0x0009
REG_SYS_TOTAL_CURRENT_L1 = 0x000A
REG_SYS_TOTAL_CURRENT_L2 = 0x000B
REG_SYS_TOTAL_CURRENT_L3 = 0x000C
REG_SYS_UNUSED_POWER = 0x000D
REG_SYS_ARTICLE_NUM = 0x0020
REG_SYS_SERIAL_NUM = 0x0030
LEN_STRING_REGISTERS = 16 

ADDR_LP1_BASE = 0x0100
ADDR_LP2_BASE = 0x0200

OFFSET_MAX_POWER = 0x0000
OFFSET_STATUS_WORD = 0x001
OFFSET_POWER = 0x002
OFFSET_CURRENT_L1 = 0x003
OFFSET_CURRENT_L2 = 0x004
OFFSET_CURRENT_L3 = 0x005
OFFSET_CHARGING_TIME = 0x006
OFFSET_ENERGY = 0x008
OFFSET_PHASE_MODE = 0x009
OFFSET_PHASE_SWITCHES = 0x00A
OFFSET_ERROR_CODE = 0x00B
OFFSET_STATUS_CODE = 0x00C
OFFSET_VOLTAGE_L1 = 0x00D
OFFSET_VOLTAGE_L2 = 0x00E
OFFSET_VOLTAGE_L3 = 0x00F
OFFSET_RFID_TAG = 0x010
OFFSET_METER_READING = 0x018
OFFSET_DERATING_STATUS = 0x01A

# --- STATUS MAPPINGS ---
CHARGE_POINT_ERROR_CODES = {
    0: "NoError", 1: "ConnectorLockFailure", 2: "EVCommunicationError", 3: "GroundFailure",
    4: "HighTemperature", 5: "InternalError", 6: "LocalListConflict", 7: "NoError",
    8: "OtherError", 9: "OverCurrentFailure", 10: "PowerMeterFailure", 11: "PowerSwitchFailure",
    12: "ReaderFailure", 13: "ResetFailure", 14: "UnderVoltage", 15: "OverVoltage", 16: "WeakSignal"
}
DERATING_STATUS_MAP = {
    0: "No derating", 1: "1st Stage", 2: "2nd Stage", 3: "Charging Stopped (OverTemp)", 4: "Sensor Error"
}

# --- SMART CHARGING LOGIC CONSTANTS ---

# Modes
MODE_FAST = "Schnellladen (11kW)"
MODE_LIMITED = "Begrenztes Laden"
MODE_SOLAR = "Solarladen"
CHARGING_MODES = [MODE_FAST, MODE_LIMITED, MODE_SOLAR]

# Defaults
DEFAULT_FAST_POWER = 11000  # 11 kW
DEFAULT_LIMITED_POWER = 3600 # 3.6 kW
DEFAULT_SOLAR_BUFFER = 500   # Watt Abzug vom Überschuss
DEFAULT_ZOE_MIN_CURRENT = 8  # Ampere

# Timers (Minuten)
TIME_HOLD_RISING = 20
TIME_HOLD_FALLING = 15

# Thresholds
THRESHOLD_DROP_PERCENT = 10 # Sofortige Anpassung bei > 10% Abfall